[project]
name = "03-dynamic-tool-filter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.20.0",
    "openai-agents>=0.5.0",
]
